[package]
name = "fronty"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "0.7.4"
serde_json = "1.0.41"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
rustc-hash = "1.0.1"
futures = "0.1.29"
serde = "1.0.101"
